import {requireAdmin} from '@/lib/admin';
import {redirect} from 'next/navigation';
import {type TicketEvent,type PaymentSettings} from '@/lib/tickets';
import AccountHeader from '@/components/account-header';
import SubmitButton from '@/components/submit-button';
import {saveTicketEvent,saveTicketPayment,deleteTicketEvent} from '../actions';
export const dynamic='force-dynamic';
function localDate(value:string|null){return value?new Date(new Date(value).getTime()+3*60*60*1000).toISOString().slice(0,16):'';}
function EventForm({event}:{event?:TicketEvent}) {
 return <><form action={saveTicketEvent} className="settings-form"><input type="hidden" name="id" value={event?.id??''}/><label>Title<input name="title" defaultValue={event?.title} required maxLength={150}/></label><label>Description<textarea name="description" defaultValue={event?.description} maxLength={1500} rows={3}/></label><label>Location<input name="venue" defaultValue={event?.venue??'Bora Cafe, Ground Floor, Jeddah'} required maxLength={250}/></label><div className="form-row"><label>Date & time (Saudi Arabia)<input name="starts_at" type="datetime-local" defaultValue={localDate(event?.starts_at??null)}/><small>Optional. Bookings stay open until you pause or delete the event.</small></label><label>Price (SAR)<input name="price" type="number" step="0.01" min={1} max={100000} defaultValue={(event?.price_minor??5000)/100} required/></label></div>{event?.banner_url&&<img className="event-banner-preview" src={event.banner_url} alt={`Banner for ${event.title}`}/>}<label>Image banner URL<input name="banner_url" defaultValue={event?.banner_url??''} maxLength={2000} placeholder="https://…"/><small>Clear this field to remove the banner.</small></label><label>Or upload a banner<input type="file" name="banner" accept="image/png,image/jpeg,image/webp"/><small>PNG, JPEG or WebP up to 4 MB. Uploading replaces the URL above.</small></label><label>Capacity<input name="capacity" type="number" min={1} max={100000} defaultValue={event?.capacity??100} required/></label><label className="check"><input type="checkbox" name="active" defaultChecked={event?.active??true}/>Open for bookings</label><SubmitButton>{event?'Save event':'Create event'}</SubmitButton></form>{event&&<form action={deleteTicketEvent} className="event-delete-form"><input type="hidden" name="id" value={event.id}/><label className="check"><input type="checkbox" name="confirm_delete" required/>Remove this event from ticket sales.</label><button type="submit" className="delete-button">Delete event</button><p>Existing orders and issued tickets remain available.</p></form>}</>;
}
export default async function Settings({searchParams}:{searchParams:Promise<{saved?:string;deleted?:string;error?:string}>}) {
 const {db,isAdmin}=await requireAdmin('/admin/tickets/settings');if(!isAdmin)redirect('/account');const query=await searchParams;
 const [eventResult,paymentResult]=await Promise.all([db.from('ticket_events').select('*').order('created_at'),db.from('ticket_payment_settings').select('*').eq('id',true).single()]);
 const payment=paymentResult.data as PaymentSettings|null;
 const events=(eventResult.data as TicketEvent[]??[]).filter(event=>!event.deleted_at);
 const needsUpgrade=events.some(event=>!Object.prototype.hasOwnProperty.call(event,'banner_url'));
 const errors:Record<string,string>={invalid:'Check the event fields and save again.',banner:'Choose a valid HTTPS image URL or PNG, JPEG or WebP file up to 4 MB.',bannerupload:'The banner could not be uploaded. Apply the event management database update and try again.',payment:'Check your payment details. Bank transfers need a valid Saudi IBAN.',delete:'Confirm event deletion and try again.',save:'The changes were not saved. Check that 003_event_management.sql has been applied.'};
 return <><AccountHeader/><main className="ticket-shell event-settings-shell"><a className="text-link" href="/admin/tickets">← Ticket desk</a><p className="eyebrow">Events & payments</p><div className="ticket-title-row"><h1>Set the stage.</h1><a className="button button-outline" href="/tickets">View ticket page ↗</a></div>{query.saved&&<p role="status">Settings saved.</p>}{query.deleted&&<p role="status">Event removed from ticket sales. Existing bookings are preserved.</p>}{query.error&&<p role="alert">{errors[query.error]??errors.save}</p>}{(eventResult.error||paymentResult.error)&&<p role="alert">Run 002_ticketing.sql before configuring ticket sales.</p>}{needsUpgrade&&<p className="notice">Apply 003_event_management.sql to enable banner images, event deletion, and bookings without a date restriction. Payment details can already be edited below.</p>}<p className="settings-intro">Edit your payment instructions and events below. New events open for bookings by default. Use the switches whenever you want to pause sales.</p><div className="event-settings-layout"><section className="ticket-panel payment-settings-panel"><div className="settings-heading"><h2>Payment information</h2><span className={`status-badge ${payment?.enabled?'approved':'pending'}`}>{payment?.enabled?'Sales open':'Sales paused'}</span></div>{payment&&<form action={saveTicketPayment} className="settings-form"><label>Payee name<input name="payee" defaultValue={payment.payee} required maxLength={200}/></label><label>STC Pay number<input name="stc_pay" defaultValue={payment.stc_pay} maxLength={30}/></label><label>Bank name (optional)<input name="bank_name" defaultValue={payment.bank_name} maxLength={100}/></label><label>Saudi IBAN (optional)<input name="iban" defaultValue={payment.iban} maxLength={40} placeholder="SA…"/></label><label>Payment instructions<textarea name="instructions" defaultValue={payment.instructions} maxLength={1000} rows={3}/></label><label className="check"><input type="checkbox" name="enabled" defaultChecked={payment.enabled}/>Accept ticket purchases</label><SubmitButton>Save payment information</SubmitButton></form>}</section><div className="event-management-list">{events.map(event=><section className="ticket-panel event-editor-panel" key={event.id}><div className="settings-heading"><h2>{event.title}</h2><span className={`status-badge ${event.active?'approved':'pending'}`}>{event.active?'Open':'Paused'}</span></div><EventForm event={event}/></section>)}<section className="ticket-panel event-editor-panel new-event-panel"><p className="eyebrow">Add to the lineup</p><h2>Create an event</h2><EventForm/></section></div></div></main></>;
}
