import {requireCustomer,siteUrl} from '@/lib/customer';
import {UUID,eventDate,money,orderReference,type TicketOrder,type IssuedTicket} from '@/lib/tickets';
import {notFound} from 'next/navigation';
import QRCode from 'qrcode';
import AccountHeader from '@/components/account-header';
import OrderRefresh from '@/components/order-refresh';
import TicketScanStatus,{type ScanTicket} from '@/components/ticket-scan-status';
import {WHATSAPP} from '@/lib/site-content';
export const dynamic='force-dynamic';
export default async function OrderPage({params}:{params:Promise<{id:string}>}) {
 const {id}=await params;if(!UUID.test(id))notFound();
 const {db,user}=await requireCustomer(`/account/orders/${id}`);
 const {data,error}=await db.from('ticket_orders').select('*').eq('id',id).eq('user_id',user.id).maybeSingle();
 if(error) return <><AccountHeader/><main className="ticket-shell"><p role="alert">Unable to load this booking. Try refreshing.</p><OrderRefresh/></main></>;
 if(!data)notFound();const order=data as TicketOrder;
 const {data:ticketData,error:scanError}=await db.from('issued_tickets').select('id,order_id,seat_number,token,checked_in_at,food_redeemed_at').eq('order_id',id).order('seat_number');
 const tickets=await Promise.all(((ticketData??[]) as (IssuedTicket&ScanTicket)[]).map(async ticket=>({...ticket,qr:await QRCode.toDataURL(`${siteUrl()}/staff/scan/${ticket.token}`,{width:260,margin:3,errorCorrectionLevel:'M',color:{dark:'#171025',light:'#ffffff'}})})));
 const {data:receipt}=await db.storage.from('ticket-receipts').createSignedUrl(order.receipt_path,300);
 return <><AccountHeader/><main className="ticket-shell"><a className="text-link" href="/account">← All bookings</a><p className="eyebrow">Booking #{orderReference(id)}</p><h1>{order.event_title}</h1><div className="status-toolbar"><span className={`status-badge ${order.status}`}>{order.status==='pending'?'Awaiting approval':order.status}</span><OrderRefresh poll={order.status==='pending'}/></div><div className="order-detail-grid"><section className="ticket-panel"><h2>{order.status==='approved'?'You’re on the list.':order.status==='rejected'?'Your request was not approved.':'Your receipt is with the house.'}</h2><p>{order.status==='pending'?'Staff will review your payment receipt. This page checks for updates every 15 seconds while open.':order.status==='approved'?'Show each QR at the door and again at the food counter. Every ticket has one entry and one food collection. Keep this page open for a confirmation when staff scan your code.':'Read the message below. Contact Spectra about any payment already made before submitting a corrected request.'}</p>{order.review_note&&<div className="notice"><strong>Message from Spectra</strong><p>{order.review_note}</p></div>}<dl className="order-facts"><div><dt>Date</dt><dd>{eventDate(order.event_starts_at)}</dd></div><div><dt>Venue</dt><dd>{order.event_venue}</dd></div><div><dt>Tickets</dt><dd>{order.quantity} × {money(order.unit_price_minor)}</dd></div><div><dt>Total</dt><dd>{money(order.total_minor)}</dd></div><div><dt>Booked by</dt><dd>{order.customer_name}</dd></div></dl>{order.note&&<p><strong>Your note:</strong> {order.note}</p>}<a className="text-link" href={WHATSAPP}>Contact Spectra ↗</a></section><aside className="ticket-panel"><p className="eyebrow">Payment receipt</p>{receipt?<a href={receipt.signedUrl} target="_blank" rel="noopener noreferrer"><img className="receipt-preview" src={receipt.signedUrl} alt="Your submitted payment receipt"/><span className="text-link">Open receipt ↗</span></a>:<p>Receipt preview is temporarily unavailable. Refresh to try again.</p>}</aside></div>{order.status==='approved'&&<TicketScanStatus orderIds={[id]} initialTickets={tickets.map(ticket=>({id:ticket.id,order_id:ticket.order_id,seat_number:ticket.seat_number,checked_in_at:ticket.checked_in_at,food_redeemed_at:ticket.food_redeemed_at}))} initialError={scanError?(scanError.message.includes('food_redeemed_at')?'Entry and food tracking needs database update 004. Ask the site administrator to complete setup.':'Ticket activity is temporarily unavailable. We’ll keep trying.'):undefined} orders={[{id:order.id,title:order.event_title,quantity:order.quantity}]} qrImages={Object.fromEntries(tickets.map(ticket=>[ticket.id,ticket.qr]))}/>}</main></>;
}